await import("./spec.test.js");
await import("./analysis.test.js");
await import("./cli.test.js");
await import("./providers-profile.test.js");
await import("./output.test.js");
await import("./history.test.js");
await import("./project.test.js");
await import("./agent.test.js");
await import("./mcp.test.js");
